[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200